import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify/unstyled";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-900">
        <ToastContainer 
        position="top-right"       
        autoClose={3000}           
        hideProgressBar={false}    
        newestOnTop={true}         
        closeOnClick={true}        
        rtl={false}                
        pauseOnFocusLoss={false}   
        draggable={true}           
        pauseOnHover={true}       
        theme="colored"           
      />
        {children}</body>
    </html>
  );
}
